In [23]:
import pandas as pd

In [24]:
import time

In [25]:
from sqlalchemy import create_engine

In [26]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [27]:
df = pd.read_csv('green_tripdata_2019-10.csv.gz', nrows=100)

In [28]:
print(pd.io.sql.get_schema(df, name='green_taxi_trips'))

CREATE TABLE "green_taxi_trips" (
"VendorID" INTEGER,
  "lpep_pickup_datetime" TEXT,
  "lpep_dropoff_datetime" TEXT,
  "store_and_fwd_flag" TEXT,
  "RatecodeID" INTEGER,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "ehail_fee" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "payment_type" INTEGER,
  "trip_type" INTEGER,
  "congestion_surcharge" REAL
)

In [29]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [34]:
df.head(0).to_sql(name='green_taxi_trips', con=engine, if_exists='replace')

0

In [35]:
df_iter = pd.read_csv('green_tripdata_2019-10.csv.gz', iterator=True, chunksize=100000)

In [36]:
while True:
    t_start = time.time()
    
    df = next(df_iter)
    print(df)
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

    df.to_sql(name='green_taxi_data', con=engine, if_exists='append')

    t_end = time.time()

    print('inserted another chunk..., took %.3f seconds' % (t_end - t_start))

       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0             2  2019-10-01 00:26:02   2019-10-01 00:39:58                  N
1             1  2019-10-01 00:18:11   2019-10-01 00:22:38                  N
2             1  2019-10-01 00:09:31   2019-10-01 00:24:47                  N
3             1  2019-10-01 00:37:40   2019-10-01 00:41:49                  N
4             2  2019-10-01 00:08:13   2019-10-01 00:17:56                  N
...         ...                  ...                   ...                ...
99995         2  2019-10-08 15:45:56   2019-10-08 15:54:45                  N
99996         2  2019-10-08 15:43:31   2019-10-08 15:50:11                  N
99997         2  2019-10-08 15:57:26   2019-10-08 16:17:41                  N
99998         2  2019-10-08 14:58:24   2019-10-08 15:03:40                  N
99999         2  2019-10-08 15:10:20   2019-10-08 15:17:44                  N

       RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0               1           112           196                1           5.88
1               1            43           263                1           0.80
2               1           255           228                2           7.50
3               1           181           181                1           0.90
4               1            97           188                1           2.52
...           ...           ...           ...              ...            ...
99995           1            95            95                1           0.85
99996           1            74            41                1           0.53
99997           1            75           141                1           1.94
99998           1            33            33                1           0.89
99999           1            33            40                1           1.24

       fare_amount  extra  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0             18.0   0.50      0.5        0.00           0.0        NaN
1              5.0   3.25      0.5        0.00           0.0        NaN
2             21.5   0.50      0.5        0.00           0.0        NaN
3              5.5   0.50      0.5        0.00           0.0        NaN
4             10.0   0.50      0.5        2.26           0.0        NaN
...            ...    ...      ...         ...           ...        ...
99995          7.0   0.00      0.5        0.00           0.0        NaN
99996          6.0   0.00      0.5        0.00           0.0        NaN
99997         13.0   0.00      0.5        2.98           0.0        NaN
99998          6.0   0.00      0.5        1.36           0.0        NaN
99999          7.0   0.00      0.5        0.00           0.0        NaN

       improvement_surcharge  total_amount  payment_type  trip_type  \
0                        0.3         19.30             2        1.0
1                        0.3          9.05             2        1.0
2                        0.3         22.80             2        1.0
3                        0.3          6.80             2        1.0
4                        0.3         13.56             1        1.0
...                      ...           ...           ...        ...
99995                    0.3          7.80             2        1.0
99996                    0.3          6.80             2        1.0
99997                    0.3         19.53             1        1.0
99998                    0.3          8.16             1        1.0
99999                    0.3          7.80             2        1.0

       congestion_surcharge
0                      0.00
1                      0.00
2                      0.00
3                      0.00
4                      0.00
...                     ...
99995                  0.00
99996                  0.00
99997                  2.75
99998                  0.00
99999                  0.00

[100000 rows x 20 columns]
inserted another chunk..., took 7.366 seconds
        VendorID lpep_pickup_datetime lpep_dropoff_datetime  \
100000         2  2019-10-08 15:30:23   2019-10-08 15:37:34
100001         2  2019-10-08 15:17:48   2019-10-08 15:26:33
100002         2  2019-10-08 16:01:41   2019-10-08 16:29:08
100003         1  2019-10-08 15:54:49   2019-10-08 15:59:37
100004         2  2019-10-08 15:14:39   2019-10-08 15:30:24
...          ...                  ...                   ...
199995         2  2019-10-16 18:57:30   2019-10-16 19:02:21
199996         2  2019-10-16 18:14:01   2019-10-16 18:21:06
199997         2  2019-10-16 18:09:10   2019-10-16 18:17:22
199998         2  2019-10-16 18:19:29   2019-10-16 18:53:57
199999         2  2019-10-16 18:13:44   2019-10-16 18:43:16

       store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  \
100000                  N           1            65            66
100001                  N           1           226           260
100002                  N           1           226           161
100003                  N           1           181           181
100004                  N           1           179           223
...                   ...         ...           ...           ...
199995                  N           1           134            28
199996                  N           1           244           243
199997                  N           1           181            25
199998                  N           1            25            89
199999                  N           1            75           141

        passenger_count  trip_distance  fare_amount  extra  mta_tax  \
100000                1           0.95          6.5    0.0      0.5
100001                1           1.69          8.0    0.0      0.5
100002                1           3.41         18.0    0.0      0.5
100003                1           0.60          5.0    1.0      0.5
100004                1           1.20         10.5    0.0      0.5
...                 ...            ...          ...    ...      ...
199995                5           0.53          5.0    1.0      0.5
199996                1           2.32          9.0    1.0      0.5
199997                1           1.39          7.5    1.0      0.5
199998                1           4.84         23.5    1.0      0.5
199999                6           2.35         18.0    1.0      0.5

        tip_amount  tolls_amount  ehail_fee  improvement_surcharge  \
100000        2.19           0.0        NaN                    0.3
100001        1.20           0.0        NaN                    0.3
100002        4.31           0.0        NaN                    0.3
100003        0.00           0.0        NaN                    0.3
100004        0.00           0.0        NaN                    0.3
...            ...           ...        ...                    ...
199995        1.20           0.0        NaN                    0.3
199996        0.00           0.0        NaN                    0.3
199997        0.00           0.0        NaN                    0.3
199998        5.06           0.0        NaN                    0.3
199999        4.51           0.0        NaN                    0.3

        total_amount  payment_type  trip_type  congestion_surcharge
100000          9.49             1          1                  0.00
100001         10.00             1          1                  0.00
100002         25.86             1          1                  2.75
100003          6.80             2          1                  0.00
100004         11.30             2          1                  0.00
...              ...           ...        ...                   ...
199995          8.00             1          1                  0.00
199996         10.80             2          1                  0.00
199997          9.30             2          1                  0.00
199998         30.36             1          1                  0.00
199999         27.06             1          1                  2.75

[100000 rows x 20 columns]
inserted another chunk..., took 8.617 seconds
        VendorID lpep_pickup_datetime lpep_dropoff_datetime  \
200000         2  2019-10-16 18:12:27   2019-10-16 18:23:36
200001         2  2019-10-16 18:31:44   2019-10-16 18:41:29
200002         2  2019-10-16 18:56:17   2019-10-16 19:26:07
200003         2  2019-10-16 18:16:49   2019-10-16 19:02:30
200004         2  2019-10-16 18:06:12   2019-10-16 18:17:27
...          ...                  ...                   ...
299995         2  2019-10-24 19:08:16   2019-10-24 19:20:44
299996         2  2019-10-24 19:38:18   2019-10-24 19:50:16
299997         2  2019-10-24 19:13:58   2019-10-24 19:24:54
299998         2  2019-10-24 19:04:27   2019-10-24 19:08:39
299999         2  2019-10-24 19:19:06   2019-10-24 19:28:30

       store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  \
200000                  N           1            95            95
200001                  N           1            95            28
200002                  N           1            95           180
200003                  N           1            74           142
200004                  N           1           130            10
...                   ...         ...           ...           ...
299995                  N           1           130            10
299996                  N           1            95           102
299997                  N           1            75           239
299998                  N           1           255           112
299999                  N           1            95            95

        passenger_count  trip_distance  fare_amount  extra  mta_tax  \
200000                1           0.87          8.5    1.0      0.5
200001                1           1.86          8.5    1.0      0.5
200002                1           5.05         22.0    1.0      0.5
200003                1           3.75         26.5    1.0      0.5
200004                1           2.06          9.5    1.0      0.5
...                 ...            ...          ...    ...      ...
299995                2           2.47         11.0    1.0      0.5
299996                1           2.57         11.0    1.0      0.5
299997                1           1.88          9.5    1.0      0.5
299998                1           0.80          5.0    1.0      0.5
299999                6           1.07          7.5    1.0      0.5

        tip_amount  tolls_amount  ehail_fee  improvement_surcharge  \
200000        0.00           0.0        NaN                    0.3
200001        0.00           0.0        NaN                    0.3
200002        1.00           0.0        NaN                    0.3
200003        6.21           0.0        NaN                    0.3
200004        2.26           0.0        NaN                    0.3
...            ...           ...        ...                    ...
299995        1.00           0.0        NaN                    0.3
299996        0.00           0.0        NaN                    0.3
299997        0.00           0.0        NaN                    0.3
299998        1.36           0.0        NaN                    0.3
299999        1.86           0.0        NaN                    0.3

        total_amount  payment_type  trip_type  congestion_surcharge
200000         10.30             2        1.0                  0.00
200001         10.30             2        1.0                  0.00
200002         24.80             1        1.0                  0.00
200003         37.26             1        1.0                  2.75
200004         13.56             1        1.0                  0.00
...              ...           ...        ...                   ...
299995         13.80             1        1.0                  0.00
299996         12.80             2        1.0                  0.00
299997         14.05             2        1.0                  2.75
299998          8.16             1        1.0                  0.00
299999         11.16             1        1.0                  0.00

[100000 rows x 20 columns]
inserted another chunk..., took 8.643 seconds
        VendorID lpep_pickup_datetime lpep_dropoff_datetime  \
300000       2.0  2019-10-24 20:01:56   2019-10-24 20:18:56
300001       2.0  2019-10-24 19:13:43   2019-10-24 19:21:57
300002       2.0  2019-10-24 19:25:01   2019-10-24 19:39:17
300003       2.0  2019-10-24 19:27:49   2019-10-24 19:40:27
300004       2.0  2019-10-24 19:15:20   2019-10-24 19:26:37
...          ...                  ...                   ...
399995       NaN  2019-10-06 15:04:00   2019-10-06 15:16:00
399996       NaN  2019-10-06 15:47:00   2019-10-06 16:13:00
399997       NaN  2019-10-06 15:27:00   2019-10-06 16:35:00
399998       NaN  2019-10-06 15:45:00   2019-10-06 16:36:00
399999       NaN  2019-10-06 15:42:00   2019-10-06 16:17:00

       store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  \
300000                  N         1.0            95            95
300001                  N         1.0           116           244
300002                  N         1.0           244           166
300003                  N         1.0            66            97
300004                  N         1.0            65            97
...                   ...         ...           ...           ...
399995                NaN         NaN           215           139
399996                NaN         NaN           168            74
399997                NaN         NaN            86           169
399998                NaN         NaN           122            25
399999                NaN         NaN            16           170

        passenger_count  trip_distance  fare_amount  extra  mta_tax  \
300000              6.0           2.32        12.50   1.00      0.5
300001              1.0           1.47         7.50   1.00      0.5
300002              1.0           3.18        13.00   1.00      0.5
300003              1.0           1.62         9.50   1.00      0.5
300004              1.0           1.14         8.50   1.00      0.5
...                 ...            ...          ...    ...      ...
399995              NaN           2.46        18.75   2.75      0.5
399996              NaN           3.10        19.00   0.00      0.5
399997              NaN          24.67        64.94   5.50      0.5
399998              NaN          14.17        55.12   5.50      0.5
399999              NaN          14.20        39.74   2.75      0.5

        tip_amount  tolls_amount  ehail_fee  improvement_surcharge  \
300000        0.00          0.00        NaN                    0.3
300001        1.86          0.00        NaN                    0.3
300002        3.70          0.00        NaN                    0.3
300003        2.26          0.00        NaN                    0.3
300004        2.06          0.00        NaN                    0.3
...            ...           ...        ...                    ...
399995        0.00          0.00        NaN                    0.0
399996        2.50          0.00        NaN                    0.0
399997        0.00          6.12        NaN                    0.0
399998        0.00          0.00        NaN                    0.0
399999        0.00          6.12        NaN                    0.0

        total_amount  payment_type  trip_type  congestion_surcharge
300000         14.30           1.0        1.0                   0.0
300001         13.11           1.0        1.0                   0.0
300002         18.50           1.0        1.0                   0.0
300003         13.56           1.0        1.0                   0.0
300004         12.36           1.0        1.0                   0.0
...              ...           ...        ...                   ...
399995         22.00           NaN        NaN                   NaN
399996         22.00           NaN        NaN                   NaN
399997         77.06           NaN        NaN                   NaN
399998         61.12           NaN        NaN                   NaN
399999         49.11           NaN        NaN                   NaN

[100000 rows x 20 columns]

/tmp/ipykernel_9096/1712417391.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = next(df_iter)

inserted another chunk..., took 8.600 seconds
        VendorID lpep_pickup_datetime lpep_dropoff_datetime  \
400000       NaN  2019-10-06 15:38:00   2019-10-06 16:24:00
400001       NaN  2019-10-06 15:22:00   2019-10-06 15:51:00
400002       NaN  2019-10-06 15:46:00   2019-10-06 16:42:00
400003       NaN  2019-10-06 15:34:00   2019-10-06 15:51:00
400004       NaN  2019-10-06 15:40:00   2019-10-06 16:09:00
...          ...                  ...                   ...
476381       NaN  2019-10-31 23:30:00   2019-11-01 00:00:00
476382       NaN  2019-10-31 23:03:00   2019-10-31 23:24:00
476383       NaN  2019-10-31 23:02:00   2019-10-31 23:23:00
476384       NaN  2019-10-31 23:42:00   2019-10-31 23:56:00
476385       NaN  2019-10-31 23:23:00   2019-10-31 23:56:00

        store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  \
400000                 NaN         NaN            42           225
400001                 NaN         NaN           235           159
400002                 NaN         NaN            76           145
400003                 NaN         NaN           259           242
400004                 NaN         NaN           160           148
...                    ...         ...           ...           ...
476381                 NaN         NaN            65           102
476382                 NaN         NaN           129           136
476383                 NaN         NaN            61           222
476384                 NaN         NaN            76            39
476385                 NaN         NaN            56           215

        passenger_count  trip_distance  fare_amount  extra  mta_tax  \
400000              NaN          12.43        25.85   5.50      0.5
400001              NaN           3.71        28.32   2.75      0.5
400002              NaN           7.61        33.81   2.75      0.5
400003              NaN           5.17        24.43   2.75      0.5
400004              NaN           7.07        31.58   2.75      0.5
...                 ...            ...          ...    ...      ...
476381              NaN           7.04        29.57   2.75      0.5
476382              NaN           0.00        39.83   2.75      0.5
476383              NaN           3.90        23.11   2.75      0.5
476384              NaN           3.08        15.23   2.75      0.5
476385              NaN           6.84        36.12   2.75      0.5

        tip_amount  tolls_amount  ehail_fee  improvement_surcharge  \
400000         0.0          6.12        NaN                    0.0
400001         0.0          0.00        NaN                    0.0
400002         0.0          0.00        NaN                    0.0
400003         0.0          0.00        NaN                    0.0
400004         0.0          0.00        NaN                    0.0
...            ...           ...        ...                    ...
476381         0.0          0.00        NaN                    0.0
476382         0.0          6.12        NaN                    0.0
476383         0.0          0.00        NaN                    0.0
476384         0.0          0.00        NaN                    0.0
476385         0.0          0.00        NaN                    0.3

        total_amount  payment_type  trip_type  congestion_surcharge
400000         37.97           NaN        NaN                   NaN
400001         31.57           NaN        NaN                   NaN
400002         37.06           NaN        NaN                   NaN
400003         27.68           NaN        NaN                   NaN
400004         34.83           NaN        NaN                   NaN
...              ...           ...        ...                   ...
476381         32.82           NaN        NaN                   NaN
476382         49.20           NaN        NaN                   NaN
476383         26.36           NaN        NaN                   NaN
476384         18.48           NaN        NaN                   NaN
476385         39.67           NaN        NaN                   NaN

[76386 rows x 20 columns]
inserted another chunk..., took 4.325 seconds

StopIteration: